version: '3.8'

services:
  veggie-app:
    build: .
    volumes:
    - photos:/usr/src/app/dist/photos
    environment:
    - DATABASE_URL=mongodb://database:27017/veggie-club
    depends_on: 
    - database
  database:
    image: mongo
    volumes:
    - db:/var/lib/mongodb
  nginx:
    build:
      context: ./database-config
    ports:
    - 80:80
    volumes:
    - photos:/var/www/veggie-club
    depends_on: 
      - veggie-app

volumes:
  photos:
  db: