version: '3.8'

services:
  veggie-app:
    build: .
    environment:
    - DATABASE_URL=mongodb://database:27017/veggie-club
    depends_on: 
    - database
  database:
    image: mongo
    volumes:
    - db:/var/lib/mongodb
  nginx:
    build:
      context: ./database-config
    ports:
    - 80:80
    volumes:
    - photos:/var/www/veggie-club
    depends_on: 
    - flask
  flask:
    build:
      context: ./flask-app
      dockerfile: Dockerfile
    volumes:
    - photos:/app/static/images
    ports:
    - 5000:80
    depends_on:
    - database
    environment:
    - DATABASE_URL=mongodb://database:27017
    - DOMAIN=http://fotos.veggieclub.com.ar

volumes:
  photos:
  db:
