version: '3.8'

services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
      - URL=veggieclub.com.ar
      - SUBDOMAINS=wildcard,
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - EMAIL=fedeshih@gmail.com
      - DHLEVEL=4096
    volumes:
      - /config:/config
    restart: unless-stopped