version: '3'

services:
  nginx:
    build: .
    ports:
      - 80
    volumes: 
      - /home/sh1ft/Documents/GitHub/Veggie-Bot/src/photos/temp:/var/www/veggie-club/photos
  db:
    image: mongo
    ports: 
      - 27017
    volumes:
      - /var/lib/mongdb:/var/lib/mongodb